from .build import build_model_from_cfg
import models.Point_MAE
import models.Point_MlMAE
import models.MaskSurf
import models.MaskSurf_v2
import models.PointCAE_pointnet
import models.PointCAE_pointnet_NoT
import models.PointCAE_pointnetv2
import models.PointCAE_DGCNN
import models.PointCAE_DGCNN_partseg
import models.PointCAE_transformer
import models.PointCAE_pointnet_NoT_partseg
import models.Point_M2AE
import models.detr.build
import models.MaskFeat_transformer
import models.MaskFeat_DGCNN